In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
with open('book_vectors.pkl','rb') as f:
    book_df = pickle.load(f)

In [3]:
book_df.rename(columns={0:'vectors'}, inplace=True)
book_df.shape

(12841, 1)

In [4]:
book_df.head()

                                             vectors
0  [0.0272227, 0.0467241, 0.0097215, 0.0873694, -...
1  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
2  [0.124573, 0.105804, -0.0895081, 0.140381, -0....
3  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
4  [0.00286722, 0.0452107, 0.000550202, 0.0489288...

In [5]:
# Taking out the Null Values
index = []
vectors = []
for i in range(len(book_df)):
    try:
        if book_df.vectors[i][0]:
            index.append(i)
            vectors.append(book_df.vectors[i])
    except:
        pass

In [6]:
len(index)
len(vectors)
# len(vectors[0])

12833

In [7]:
# Making a dataframe are re-indexing based on which Nulls were taken out
vectors_df = pd.DataFrame(vectors)
vectors_df['ind'] = index
vectors_df = vectors_df.set_index('ind',drop=True)

In [8]:
# Now drop the np.NaN values, this is different from the null values
vectors_df_drop = vectors_df.dropna(how='any', axis=0)

In [9]:
vectors_df_drop.head()

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
ind,,,,,,,,,,,,,,,,,,,,,
0,0.027223,0.046724,0.009721,0.087369,-0.055040,0.019433,0.064942,-0.029855,0.034339,0.071453,...,-0.098758,0.034245,-0.102580,0.028409,-0.029151,0.019838,-0.000978,-0.023733,0.014560,0.049439
2,0.124573,0.105804,-0.089508,0.140381,-0.103394,-0.007946,-0.032440,0.103668,0.091370,0.056610,...,-0.178711,-0.055023,-0.001526,0.134705,-0.021851,0.001282,0.102638,-0.161133,0.065552,0.051544
4,0.002867,0.045211,0.000550,0.048929,-0.019251,0.061453,0.029567,-0.066271,0.053399,-0.000801,...,-0.069753,0.021145,-0.128650,-0.005058,-0.087099,-0.043062,-0.028295,-0.026790,-0.026080,0.034757
5,0.052278,0.051855,0.005532,0.031356,-0.039453,0.011165,0.049956,-0.089076,0.103491,0.081849,...,-0.050837,-0.012183,-0.108181,0.006611,-0.037543,0.007142,0.012563,-0.042231,0.056785,0.016661
7,0.076089,0.088569,0.035574,0.027360,-0.038722,0.038192,-0.002572,-0.094684,0.037956,0.089953,...,-0.065434,0.008164,-0.122080,0.011423,-0.063412,-0.005924,-0.020391,-0.046497,0.059100,0.027759

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
# Compute cosine similarity
dists = cosine_similarity(vectors_df_drop)

In [12]:
# Make DataFrame and re-index based on the book number
dists = pd.DataFrame(dists, columns=vectors_df_drop.index)
dists.set_index(vectors_df_drop.index, inplace=True)

In [122]:
dists.head()

ind,0,2,4,5,7,8,9,11,13,14,...,12831,12832,12833,12834,12835,12836,12837,12838,12839,12840
ind,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.357981,0.729642,0.818917,0.823729,0.805947,0.824634,0.841399,0.772414,0.666084,...,0.789451,0.765470,0.722895,0.840243,0.762018,0.672150,0.809029,0.816344,0.786533,0.763153
2,0.357981,1.000000,0.227418,0.356883,0.326750,0.339815,0.336008,0.362137,0.309209,0.216561,...,0.342589,0.262912,0.251776,0.310246,0.248503,0.360518,0.302208,0.360881,0.380430,0.349625
4,0.729642,0.227418,1.000000,0.735601,0.708623,0.678365,0.694127,0.754363,0.732060,0.641127,...,0.732619,0.682938,0.764691,0.757435,0.640164,0.536270,0.720449,0.690878,0.720604,0.673849
5,0.818917,0.356883,0.735601,1.000000,0.892775,0.878517,0.826004,0.864786,0.828427,0.721308,...,0.840339,0.804298,0.748449,0.867730,0.764731,0.663280,0.870823,0.868561,0.831503,0.844331
7,0.823729,0.326750,0.708623,0.892775,1.000000,0.963332,0.851200,0.877786,0.807813,0.722040,...,0.836286,0.786279,0.729671,0.883936,0.709615,0.669294,0.936672,0.950997,0.819237,0.846312

In [15]:
dists.set_index(vectors_df_drop.index).head()

ind,0,2,4,5,7,8,9,11,13,14,...,12831,12832,12833,12834,12835,12836,12837,12838,12839,12840
ind,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.357981,0.729642,0.818917,0.823729,0.805947,0.824634,0.841399,0.772414,0.666084,...,0.789451,0.765470,0.722895,0.840243,0.762018,0.672150,0.809029,0.816344,0.786533,0.763153
2,0.357981,1.000000,0.227418,0.356883,0.326750,0.339815,0.336008,0.362137,0.309209,0.216561,...,0.342589,0.262912,0.251776,0.310246,0.248503,0.360518,0.302208,0.360881,0.380430,0.349625
4,0.729642,0.227418,1.000000,0.735601,0.708623,0.678365,0.694127,0.754363,0.732060,0.641127,...,0.732619,0.682938,0.764691,0.757435,0.640164,0.536270,0.720449,0.690878,0.720604,0.673849
5,0.818917,0.356883,0.735601,1.000000,0.892775,0.878517,0.826004,0.864786,0.828427,0.721308,...,0.840339,0.804298,0.748449,0.867730,0.764731,0.663280,0.870823,0.868561,0.831503,0.844331
7,0.823729,0.326750,0.708623,0.892775,1.000000,0.963332,0.851200,0.877786,0.807813,0.722040,...,0.836286,0.786279,0.729671,0.883936,0.709615,0.669294,0.936672,0.950997,0.819237,0.846312

In [16]:
books = pd.read_json('Projects/4Fletcher/books_data.json')
books = books.reset_index()
books = books.drop('index',axis=1)
books = books[books['Summary']!=None]

In [131]:
books[books['Published_date'] > 2000]

,Author,Book_Title,Genre,Published_date,Summary
2,Robert Wilson,The Hidden Assassins,"[Crime Fiction, Mystery, Fiction]",2006,The novel tackles themes of terrorism.
3,Cecily von Ziegesar,Lucky,[Young adult literature],2007,Jenny Humphrey has attended some crazy partie...
4,Alexander McCall Smith,The Full Cupboard of Life,"[Mystery, Detective fiction]",2003,Mma Ramotswe is now engaged to the mechanic M...
7,Dave Wolverton,Wizardborn,"[Speculative fiction, Fantasy, High fantasy]",2001,After Raj Ahten attempts to murder the Earth ...
8,Dave Wolverton,The Lair of Bones,"[Speculative fiction, Fantasy, High fantasy]",2003,In order to save mankind and all life on Eart...
13,Margaret Haddix,Among the Brave,"[Science Fiction, Children's literature, Specu...",2004,The fifth book starts off directly where the ...
15,Alexander McCall Smith,Espresso Tales,"[Serial, Fiction]",2005,"Pat is still sharing a flat with Bruce, the g..."
17,Chuck Palahniuk,Rant: The Oral Biography of Buster Casey,"[Satire, Fiction, Novel]",2007,Buster Casey is born in the rural town of Mid...
21,Margaret Haddix,Among the Enemy,"[Science Fiction, Children's literature, Specu...",2005,"Matthias, Percy, and Alia, (from Among the Be..."
22,Margaret Haddix,Among the Free,"[Science Fiction, Children's literature, Specu...",2006,Luke Garner is an illegal third child along w...
24,Laurell K. Hamilton,A Stroke of Midnight,"[Horror, Speculative fiction, Fantasy, Fiction...",2005,Following on almost immediately from the even...
25,Laurell K. Hamilton,Seduced by Moonlight,"[Horror, Speculative fiction, Fantasy, Fiction...",2004,Seduced by Moonlight begins shortly after the...
27,Laurell K. Hamilton,A Caress of Twilight,"[Horror, Speculative fiction, Fantasy, Fiction]",2002,A Caress of Twilight begins a few months afte...
29,Laurell K. Hamilton,Mistral's Kiss,"[Horror, Speculative fiction, Fantasy]",2006,Meredith wakes up from a dream where she is g...
31,David Wellington,Monster Planet,"[Speculative fiction, Horror]",2005,Monster Planet takes place twelve years after...
35,E. L. Konigsburg,The Outcasts of 19 Schuyler Place,[Young adult literature],2004,Twelve-year-old Margaret Rose Kane is sent to...
36,Will Self,The Book of Dave,"[Science Fiction, Fiction, Novel]",2006,"Contemporary narrative: Dave Rudman, a London..."
38,Natsuo Kirino,Out,"[Crime Fiction, Mystery, Fiction, Suspense]",2004,"The novel tells the tales of four women, work..."
40,Daniel Handler,Adverbs,"[Fiction, Romance novel, Novel]",2006,"In ""Immediately,"" a man leaves his girlfriend..."
45,Maxine Paetro,4th of July,"[Crime Fiction, Mystery, Fiction, Suspense]",2005,When Lindsay Boxer gets a lead on a recent mu...
52,Philip K. Dick,Voices From the Street,"[Speculative fiction, Fiction, Novel]",2007,Official synopsis: :Stuart Hadley is a young ...
59,N/A,Joker in the pack,[Fiction],2007,The novel describes the student life of Shekh...
60,"L. E. Modesitt, Jr.",The Octagonal Raven,"[Science Fiction, Speculative fiction]",2001,The Octagonal Raven is set in the distant fut...
66,Nick Sagan,Edenborn,"[Science Fiction, Speculative fiction, Fiction]",2004,"In the aftermath of a global plague, a group ..."
67,Cornelia Funke,Inkdeath,"[Young adult literature, Speculative fiction, ...",2008,"Inkdeath picks up with the now immortal, but ..."
68,Philip Kerr,The Blue Djinn of Babylon,"[Speculative fiction, Fantasy, Children's lite...",2006,"After having promised their mother, Layla, no..."
70,N/A,The Sky Village,"[Young adult literature, Science Fiction, Fant...",2008,"High above a troubled China, where animals ba..."
94,Cheryl Kaye Tardif,Whale Song,"[Fiction, Novel]",2010,Thirteen years prior to the start of the book...
102,Samantha Power,A Problem from Hell: America and the Age of Ge...,[Non-fiction],2003,Power begins with an outline of the internati...
114,Julia Golding,Secret of The Sirens,"[Speculative fiction, Fantasy]",2006,'The Secret of the Sirens takes place in the ...
...,...,...,...,...,...
12715,D.J. MacHale,Pendragon Book 8,[Fantasy],2007,Bobby and Courtney arrive on Third Earth only...
12727,Mags L Halliday,Warring States,"[Science Fiction, Speculative fiction]",2005,Cousin Octavia of Faction Paradox has come to...
12730,N/A,"South Park and Philosophy: Bigger, Longer, and...","[Philosophy, Non-fiction]",2007,The book includes an article about the charac...
12741,Vince Flynn,Consent to Kill,[Fiction],2005,"In Flynn's previous novel, Memorial Day, CIA ..."
12742,Neal Asher,Hilldiggers,"[Science Fiction, Speculative fiction]",2007,The novel describes the initial diplomatic co...
12747,N/A,Sara Payne: A Mother's Story,"[Autobiography, True crime]",2004,The autobiography covers the abduction and mu...
12752,A. Lee Martinez,Gil's All Fright Diner,"[Science Fiction, Speculative fiction]",2005,"In the backwoods southern town of Rockwood, a..."
12757,Glen Duncan,"I, Lucifer","[Speculative fiction, Fiction]",2003,"In I, Lucifer, God presents the devil with a ..."
12765,Chris Riddell,The Curse of the Gloamglozer,"[Speculative fiction, Fantasy, Children's lite...",2001,"Quint, the fourteen-year-old only remaining s..."
12780,T. A. Barron,Shadows on the Stars,"[Speculative fiction, Fantasy]",2005,"In the previous book, ""Child of the Dark Prop..."
12784,Iain Banks,Matter,"[Science Fiction, Speculative fiction]",2008,The book follows the experiences of three mem...
12785,Patricia Bray,Devlin's Luck,"[Speculative fiction, Fantasy]",2002,Devlin Stonehand is an ex-metalsmith and ex-f...
12792,Ken MacLeod,Learning the World,"[Science Fiction, Speculative fiction, Fiction...",2005,"The novel is a first contact story, following..."
12794,Orson Scott Card,Shadow of the Hegemon,"[Science Fiction, Speculative fiction, Fiction]",2001,"In Shadow of the Hegemon, all of the Battle S..."
12798,Ann Patchett,Bel Canto,"[Thriller, Fiction, Romance novel]",2001,"Set in an unnamed country, the story begins a..."
12799,Laura Albert,Sarah,[Novel],2001,Cherry Vanilla passes himself off as a virgin...
12803,John Flanagan,The Ruins of Gorlan,"[Speculative fiction, Fantasy]",2004,"Morgarath, the angry, evil ,exiled lord of th..."
12804,John Flanagan,The Burning Bridge,"[Speculative fiction, Fantasy]",2005,"On a special mission for the Ranger Corps, Wi..."
12808,Nora Roberts,Eternity in Death,[Crime Fiction],2007,Tiara Kent lights several candles in her room...
12811,Barbara Mertz,Lord of the Silent,"[Mystery, Historical novel]",2001,"In this installment, which takes place during..."
12812,Barbara Mertz,The Golden One,"[Mystery, Speculative fiction, Historical novel]",2002,The Golden One is a combination of two storie...
12813,Barbara Mertz,Children of the Storm,"[Mystery, Historical novel]",2003,The 1919 season opens with the Vandergelts an...
12814,Barbara Mertz,Guardian of the Horizon,"[Mystery, Historical novel]",2004,"The story begins in summer, 1907, ten years a..."
12815,Barbara Mertz,The Serpent on the Crown,"[Mystery, Historical novel]",2005,"In 1922, the Emersons are excavating at Deir ..."
12816,Barbara Mertz,Tomb of the Golden Bird,"[Mystery, Historical novel]",2006,Howard Carter returns as a featured character...
12819,Ed Stark,Fantastic Locations: Dragondown Grotto,[Role-playing game],2007,"In the first chapter, Spawnscale Nursery, the..."
12824,Dan Simmons,Olympos,"[Science Fiction, Speculative fiction, Novel]",2005,The novel centers on three main character gro...
12831,David L. Seidman,The First Casualty,"[Crime Fiction, Speculative fiction, Mystery, ...",2005,"In June 1917, whilst recovering from shell sh..."
12834,Philip Kerr,The Akhenaten Adventure,"[Children's literature, Fantasy, Speculative f...",2004,John and Philippa Gaunt lead an upper class l...
12839,Brian Keene,The Conqueror Worms,"[Speculative fiction, Horror, Fiction]",2006,Teddy Garnett tells this story of a global fl...

In [ ]:
dists

In [46]:
books['Book_Title'][2]

u'The Hidden Assassins'

In [159]:
def bookender(title):
    title_index = books[books['Book_Title']=='{}'.format(title)].index.tolist()[0]
    top_5_values = dists[title_index][:].sort_values(ascending=False)[:6]
    values_indexes = dists[title_index][:].sort_values(ascending=False).index.tolist()
    top_5_indexes = values_indexes[:6]
    top_5_books = books.iloc[top_5_indexes]
    print top_5_values
    return top_5_books

In [161]:
bookender('Bel Canto')

ind
12798    1.000000
2339     0.887298
10342    0.883713
7923     0.883078
3505     0.882075
9227     0.881482
Name: 12798, dtype: float64

,Author,Book_Title,Genre,Published_date,Summary
12798,Ann Patchett,Bel Canto,"[Thriller, Fiction, Romance novel]",2001,"Set in an unnamed country, the story begins a..."
2339,Ayn Rand,We the Living,"[Autobiographical novel, Historical fiction, F...",0,"The story takes place from 1922 to 1925, in p..."
10342,Mario Puzo,Omertà,"[Thriller, Crime Fiction]",2000,The book begins with the death of Don Zeno in...
7923,Robert A. Heinlein,Farnham's Freehold,[Science Fiction],1964,"Hugh Farnham, a middle-aged man, holds a brid..."
3505,Jack L. Chalker,Twilight at the Well of Souls,"[Science Fiction, Speculative fiction, Fiction]",1980,The plot of Twilight at the Well of Souls is ...
9227,Anchee Min,Becoming Madame Mao,[Historical novel],2001,Madame Mao was born to a very poor family aro...

In [130]:
books.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12841 entries, 0 to 12840
Data columns (total 5 columns):
Author            12841 non-null object
Book_Title        12841 non-null object
Genre             12841 non-null object
Published_date    12841 non-null int64
Summary           12841 non-null object
dtypes: int64(1), object(4)
memory usage: 601.9+ KB

In [163]:
!pip install wordcloud

Collecting wordcloud
  Downloading wordcloud-1.2.1.tar.gz (165kB)
    100% |████████████████████████████████| 174kB 1.8MB/s
Building wheels for collected packages: wordcloud
  Running setup.py bdist_wheel for wordcloud ... - \ | / - done
  Stored in directory: /Users/veenakumar/Library/Caches/pip/wheels/29/9a/a9/86dcbbd5a7b6ace25887e4351a0136ea6dfcc0dd7de0a51357
Successfully built wordcloud
Installing collected packages: wordcloud
Successfully installed wordcloud-1.2.1
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.